### ISSUE TITLE
Get self-host server from CSC

### ISSUE THREAD

**Issue by QuantumManiac** [waterloo-rocketry/minerva-rewrite#1]

**Comment by PCModeActivate** [comment]
Waiting from email reply.

**Comment by QuantumManiac** [comment]
CSC has gotten back to us and created a `waterloorocketry` group. In addition, team files can be found in `/users/uwrocketryteam.

The following users have been made "club representitives", allowing them to manage access to the team account and group:

@QuantumManiac
@PCModeActivate 
@KavinSatheeskumar 
@Darth-Raazi 

Please reach out to them if you need access to the team account for yourself.
