### ISSUE TITLE
Set up formatting/linting

### ISSUE THREAD

**Issue by QuantumManiac** [waterloo-rocketry/minerva-rewrite#13]
Tasks:
- [x] Add ESLint and Prettier as dev dependencies
- [x] Add the ESLint and Prettier extensions as recommended extensions for the repo for VSCode
- [x] #28

**Comment by billyao021031** [comment]
Task1: Add ESLInt and Prettier
<img width="492" alt="Screen Shot 2023-10-09 at 1 47 34 AM" src="https://github.com/waterloo-rocketry/minerva-rewrite/assets/97845908/57307d4b-6109-4233-bfc2-3d05b13a3e0c">
Task2: Add ESLint and Prettier as recommended extension
<img width="461" alt="Screen Shot 2023-10-09 at 1 48 15 AM" src="https://github.com/waterloo-rocketry/minerva-rewrite/assets/97845908/523bae8e-a897-40c3-83b5-16182ba49e15">
Task3: Create a format command 
<img width="691" alt="Screen Shot 2023-10-09 at 1 48 39 AM" src="https://github.com/waterloo-rocketry/minerva-rewrite/assets/97845908/99ffe434-59f5-4726-a261-1da75c061b37">

Question:
1. Sorry that accidentally converted the third task into an issue and have closed it. 
2. I have created a .eslintrc.json for ESLint and .prettierrc for prettier, but within .prettierrc, we might wanna discuss the format we would like to take for the project. 
<img width="350" alt="Screen Shot 2023-10-09 at 1 50 42 AM" src="https://github.com/waterloo-rocketry/minerva-rewrite/assets/97845908/035c6805-3ad2-4a73-b5ac-bf299934af9c">
(Here I just went with a default setting)
