### ISSUE TITLE
Implement `/notify` Command for Replying to Message to Broadcast

### ISSUE THREAD

**Issue by QuantumManiac** [waterloo-rocketry/minerva-rewrite#24]
Dependencies:
- #23 

For this task, we would like to implement a `/notify` [slash command](https://slack.dev/bolt-js/concepts#commands) that you invoke in a message replying to the message you want to repost along with (optionally) some slack channel names. Minerva then posts the link of the slack message that you're replying to (essentially copying the message) to the channels that you provide, or if you didn't provide any channels, to a pre-defined list of default channels.

e.g. invoking `/notify #electrical` in the reply thread to a message would repost that message to #electrical. Omitting the `#electrical` argument would repost the message to the pre-defined list of default channels.

Implementing this command will require its slash command to be added in the Slack App Console (see [here](https://api.slack.com/interactivity/slash-commands) for more info). This will need to be done for the development instance of Minerva now, and the production instance of minerva once it is released

**Comment by Tintinnit** [comment]
It seems as though Slackbot does not allow developers to create commands in threads. I tried searching for workaround, but there doesn't seem to be one for now. If anyone can find something, feel free to open this up again and implement it.

In the meantime, our current implementation of the /notify command is already great, so I will close this issue.
